name:                log-store
version:             0.1.0.0
github:              "https://github.com/hstream-io/log-store"
license:             BSD3
author:              "Wang Bin"
maintainer:          "wangbin@emqx.io"
copyright:           "Copyright (c) 2020 EMQ Technologies Co., Ltd."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hstream-io/log-store#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- data-default
- store
- resourcet
- filepath
- directory
- transformers
- mtl
- rocksdb-haskell-bindings
- streamly

library:
  source-dirs: src
  exposed-modules:
  - Log.Store.Base
  ghc-options:
  - -W

tests:
  log-store-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - log-store
    - hspec
    - hspec-expectations
    - QuickCheck
    - temporary-resourcet

benchmarks:
  log-store-benchmark:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fprof-auto
    dependencies:
      - log-store
      - criterion
      - temporary-resourcet

